name: Update Issue Templates with Product Areas

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if Google Sheets is not accessible'
        required: false
        default: 'false'
        type: boolean
  schedule:
    # Run weekly on Mondays at 9 AM UTC to keep templates up to date
    - cron: '0 9 * * 1'

jobs:
  update-templates:
    name: Update Issue Templates
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for committing changes
      pull-requests: write  # Required for creating PRs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install googleapis

      - name: Update Issue Templates
        env:
          GOOGLE_SHEETS_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SHEETS_SERVICE_ACCOUNT_JSON }}
          FORCE_UPDATE: ${{ inputs.force_update }}
        run: |
          node .github/update-issue-templates.js

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update issue templates with latest product areas'
          title: 'Update issue templates with latest product areas'
          body: |
            This PR updates the issue templates with the latest product areas from Google Sheets.
            
            ## Changes
            - Updated product area options in all issue templates
            - Updated highlevel-teams.json with current team mappings
            
            ## Source
            Data fetched from: https://docs.google.com/spreadsheets/d/1M41yAqW5XcfMUaHA6h6ewJ6tabF_eOVoyu7JfD1iC_U/
            
            This update was automatically generated by the `update-issue-templates` workflow.
          branch: update-issue-templates
          delete-branch: true

      - name: Summary
        run: |
          if [ "${{ steps.changes.outputs.has_changes }}" == "true" ]; then
            echo "✅ Issue templates updated and PR created"
          else
            echo "ℹ️ No changes detected in issue templates"
          fi